source/mereokratos/urls.py
from django.urls import path
from mereokratos import views

app_name = 'mereokratos'

urlpatterns = [
    path('', views.index, name='index'),
]

source/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from candelabrus import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('markdownx/', include('markdownx.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('fons/', include('fons.urls')),
    path('dejure/', include('dejure.urls')),
    path('darwin/', include('darwin.urls')),
    path('nietz/', include('nietz.urls')),
    path('mereokratos/', include('mereokratos.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/mereokratos/views.py
from django.http import HttpResponse
from django.template import loader


def index(request):
    template = loader.get_template('mereokratos/index.html')
    return HttpResponse(template.render(None, request))

source/templates/mereokratos/base.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
    <link rel="shortcut icon" href="{% static "mereokratos/icon.png" %}"/>
    <link rel="stylesheet" href="{% static 'mereokratos/style.css' %}">
{% endblock %}

{% block header %}
    <a id="title-wrapper" href="{% url 'mereokratos:index' %}">
        <img id="logo" src="{% static "mereokratos/icon.svg" %}">
        <div style="display: flex; flex-direction: column">
            <span id="title">Mereokratos</span>
            <span id="subtitle">{% trans "Better representation" %}</span>
        </div>
    </a>
    <nav id="header-nav">
    </nav>
{% endblock %}

source/templates/mereokratos/index.html
{% extends 'mereokratos/base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
{% endblock %}