source/darwin/urls.py
from django.urls import path
from darwin import views

app_name = 'darwin'

urlpatterns = [
    path('', views.index, name='index'),
]

source/dejure/urls.py
from django.urls import path
from dejure import views

app_name = 'dejure'

urlpatterns = [
    path('', views.index, name='index'),
]

source/fons/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from fons import views

app_name = 'fons'

urlpatterns = [
    path('', views.index, name='index'),
    path(_('catalog'), views.catalog, name='catalog'),
    path(_('subject/<int:identifier>'), views.subject, name='subject'),
]

source/nietz/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from nietz import views

app_name = 'nietz'

urlpatterns = [
    path('', views.index, name='index'),
    path(_('concepts/'), views.concepts, name='concepts'),
    path(_('fallacies/'), views.fallacies, name='fallacies'),
    path(_('fallacies/<int:identifier>/'), views.fallacy, name='fallacy'),
]

source/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from candelabrus import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('markdownx/', include('markdownx.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('fons/', include('fons.urls')),
    path('dejure/', include('dejure.urls')),
    path('darwin/', include('darwin.urls')),
    path('nietz/', include('nietz.urls')),
    path('mereokratos/', include('mereokratos.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/balloon-css/0.5.0/balloon.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Open+Sans|Roboto|Ubuntu" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
<div id="header-wrapper">
    <header class="width-limiter">
        {% block header %}
        {% endblock %}
    </header>
</div>
<div id="center-wrapper">
    <div class="width-limiter">
        {% block content %}
        {% endblock %}
    </div>
</div>
<div id="footer-wrapper">
    <footer class="width-limiter">
        <nav id="portals">
            <a href="{% url 'index' %}" data-balloon="{% trans "Support for illumination" %}" data-balloon-pos="up">
                <img src="{% static "candelabrus/icon.svg" %}">
                <span>Candelabrus</span>
            </a>
            <a href="{% url 'fons:index' %}" data-balloon="{% trans "Know the truth" %}" data-balloon-pos="up">
                <img src="{% static "fons/icon.svg" %}">
                <span>Fons</span>
            </a>
            <a href="{% url 'nietz:index' %}" data-balloon="{% trans "Learn arguing" %}" data-balloon-pos="up">
                <img src="{% static "nietz/icon.svg" %}">
                <span>Nietz</span>
            </a>
            <a href="{% url 'dejure:index' %}" data-balloon="{% trans "Law understood" %}" data-balloon-pos="up">
                <img src="{% static "dejure/icon.svg" %}">
                <span>DeJure</span>
            </a>
            <a href="{% url 'darwin:index' %}" data-balloon="{% trans "Society evolved" %}" data-balloon-pos="up">
                <img src="{% static "darwin/icon.svg" %}">
                <span>Darwin</span>
            </a>
            <a href="{% url 'mereokratos:index' %}" data-balloon="{% trans "Better representation" %}" data-balloon-pos="up">
                <img src="{% static "mereokratos/icon.svg" %}">
                <span>Mereokratos</span>
            </a>
        </nav>
        <nav id="footer-links">
            <a href="#">FAQ</a>
            <a href="#">{% trans "Privacy" %}</a>
            <a href="#">{% trans "About" %}</a>
            <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
                <img alt="Creative Commons License" style="border-width:0"
                     src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"/>
            </a>
        </nav>
    </footer>
</div>
</body>
</html>