source/nietz/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from nietz import views

app_name = 'nietz'

urlpatterns = [
    path('', views.index, name='index'),
    path(_('concepts/'), views.concepts, name='concepts'),
    path(_('fallacies/'), views.fallacies, name='fallacies'),
    path(_('fallacies/<int:identifier>/'), views.fallacy, name='fallacy'),
]

source/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from candelabrus import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('markdownx/', include('markdownx.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('fons/', include('fons.urls')),
    path('dejure/', include('dejure.urls')),
    path('darwin/', include('darwin.urls')),
    path('nietz/', include('nietz.urls')),
    path('mereokratos/', include('mereokratos.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/nietz/models.py
from django.db import models as djm
from django.contrib.postgres import fields as pg
from markdownx.models import MarkdownxField
from colorful.fields import RGBColorField
from markdownx.utils import markdownify

from location import models as location


def fallacy_img_path(fallacy, filename):
    return f'nz/f/i/{fallacy.name.replace(" ", "_")}.{filename.split(".")[-1]}'


class GuideSection(djm.Model):
    language = djm.ForeignKey(location.Language, on_delete=djm.PROTECT)
    name = djm.CharField(max_length=100)
    index = djm.IntegerField()
    content = MarkdownxField()
    # Always points to the english guide section this has been translated from
    parent = djm.ForeignKey('self', on_delete=djm.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def content_html(self):
        return markdownify(self.content)

    class Meta:
        unique_together = [['language', 'index'], ['language', 'name']]
        ordering = ['index']


class Fallacy(djm.Model):
    # Language agnostic identifier (usually latin or english)
    name = djm.CharField(max_length=50, unique=True)
    # Fallacy variants point to their generalizations
    parent = djm.ForeignKey('self', on_delete=djm.PROTECT, null=True, blank=True)
    # A cover image
    image = djm.ImageField(upload_to=fallacy_img_path, null=True, blank=True)
    related = djm.ManyToManyField('self', blank=True)
    categories = djm.ManyToManyField('FallacyCategory', blank=True)

    def __str__(self):
        if self.parent is None:
            return self.name
        else:
            return f"{self.name} ({self.parent.name})"

    class Meta:
        verbose_name_plural = 'fallacies'
        ordering = ['name']


class LocalizedFallacy(djm.Model):
    fallacy = djm.ForeignKey(Fallacy, on_delete=djm.PROTECT)
    language = djm.ForeignKey(location.Language, on_delete=djm.PROTECT)
    name = djm.CharField(max_length=50)  # Fallacy name in this locale
    description = djm.CharField(max_length=200)  # A short description in this locale
    explanation = MarkdownxField()  # The full description in this locale
    sources = pg.ArrayField(djm.URLField(), null=True, blank=True)  # Array with external references to this fallacy

    def __str__(self):
        return f'{self.name} - {self.fallacy.name} ({self.language})'

    @property
    def explanation_html(self):
        return markdownify(self.explanation)

    class Meta:
        verbose_name_plural = 'localized fallacies'
        unique_together = [('fallacy', 'language'), ('name', 'language')]
        ordering = ['name']


class FallacyExample(djm.Model):
    parent = djm.ForeignKey(LocalizedFallacy, on_delete=djm.PROTECT, related_name="examples")
    content = MarkdownxField()
    explanation = MarkdownxField()

    @property
    def content_html(self):
        return markdownify(self.content)

    @property
    def explanation_html(self):
        return markdownify(self.explanation)

    class Meta:
        unique_together = ['parent', 'content']


def fallacy_category_img_path(fallacy_category, filename):
    return f'nz/fc/{fallacy_category.name.replace(" ", "_")}.{filename.split(".")[-1]}'


class FallacyCategory(djm.Model):
    name = djm.CharField(max_length=20)
    color = RGBColorField()
    icon = djm.ImageField(upload_to=fallacy_category_img_path, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'fallacy categories'

source/nietz/views.py
from django.utils import translation as t
from django.shortcuts import render

from nietz import models as m


def index(request):
    return render(request, 'nietz/index.html', None)


def concepts(request):
    guide = m.GuideSection.objects.filter(language__alpha2=t.get_language()).all()
    context = {'guide': guide}
    return render(request, 'nietz/concepts.html', context)


def fallacies(request):
    localized_fallacies = m.LocalizedFallacy.objects.filter(language__alpha2=t.get_language())
    untranslated_fallacies = m.LocalizedFallacy.objects \
        .filter(language__alpha2='en', fallacy__parent=None) \
        .exclude(fallacy__localizedfallacy__language__alpha2=t.get_language())

    context = {'fallacies': localized_fallacies,
               'untranslated_fallacies': untranslated_fallacies}
    return render(request, 'nietz/fallacies.html', context)


def fallacy(request, identifier):
    translations = m.LocalizedFallacy.objects.filter(fallacy_id=identifier).all()
    languages = list(map(lambda translated_fallacy: translated_fallacy.language, translations))
    language = t.get_language()
    fallacy_obj = None
    is_translated = False
    for translated_fallacy in translations:
        if translated_fallacy.language.alpha2 == language:
            fallacy_obj = translated_fallacy
            is_translated = True
            break
        if translated_fallacy.language == 'en':
            fallacy_obj = translated_fallacy

    children = m.LocalizedFallacy.objects.filter(fallacy__parent=fallacy_obj.fallacy, language__alpha2=language)
    untranslated_children = m.LocalizedFallacy.objects \
        .filter(fallacy__parent=fallacy_obj.fallacy, language__alpha2='en') \
        .exclude(fallacy__localizedfallacy__language__alpha2=language)

    related = m.LocalizedFallacy.objects.filter(fallacy__related=fallacy_obj.fallacy, language__alpha2=language)
    untranslated_related = m.LocalizedFallacy.objects \
        .filter(fallacy__related=fallacy_obj.fallacy, language__alpha2='en') \
        .exclude(fallacy__localizedfallacy__language__alpha2=language)

    context = {'fallacy': fallacy_obj,
               'languages': languages,
               'is_translated': is_translated,
               'children': children,
               'untranslated_children': untranslated_children,
               'related': related,
               'untranslated_related': untranslated_related}
    return render(request, 'nietz/fallacy.html', context)

source/templates/nietz/base.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block head %}
    <link rel="shortcut icon" href="{% static "nietz/icon.png" %}"/>
    <link rel="stylesheet" href="{% static 'nietz/style.css' %}">
{% endblock %}

{% block header %}
    <a id="title-wrapper" href="{% url 'nietz:index' %}">
        <img id="logo" src="{% static "nietz/icon.svg" %}">
        <span id="title">Nietz</span>
        <span id="subtitle">{% trans "Learn arguing" %}</span>
    </a>
    <nav id="header-nav">
        <a href="{% url 'nietz:concepts' %}">{% trans "Concepts" %}</a>
        <a href="{% url 'nietz:fallacies' %}">{% trans "Fallacies" %}</a>
        <a href="#">{% trans "Biases" %}</a>
    </nav>
{% endblock %}

source/templates/nietz/concepts.html
{% extends 'nietz/base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="formatter">
        <h1>{% trans "Basic argumentation concepts" %}</h1>
        {% blocktrans  trimmed %}
            This is a quick guide on some principles you need to know in order to know how to argue.<br>
            Consider these topics very very simplified.
            If you want to study them more extensively, consider a good philosophy book.
        {% endblocktrans %}
    </div>
    {% for section in guide %}
        <div class="concept-tab">
            <input id="{{ section.name|cut:" " }}" type="checkbox" name="tabs">
            <label for="{{ section.name|cut:" " }}">{{ section.name }}</label>
            <div class="concept-tab-content">
                <div class="formatter">{{ section.content_html|safe }}</div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

source/templates/nietz/fallacies.html
{% extends 'nietz/base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="formatter">
            <h2>{% trans "These are the most generic fallacies. Click them to learn more:" %}</h2>
        <div class="fallacies">
            {% for fallacy in fallacies %}
                <div class="fallacy{% if fallacy.fallacy.parent is not None %} child{% endif %}">
                    {% if fallacy.fallacy.image %}
                        <img src="{{ fallacy.fallacy.image.url }}"/>
                    {% else %}
                        <img src="{% static 'nietz/icon.svg' %}"/>
                    {% endif %}
                    <div>
                        <a href="{% url 'nietz:fallacy' fallacy.fallacy.id %}" class="name">{{ fallacy.name.capitalize }}</a>
                        <span class="description">{{ fallacy.description }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if untranslated_fallacies.exists %}
            <h2>{% trans "There are a few more, but they haven't been translated yet:" %}</h2>
            <div class="fallacies">
                {% for fallacy in untranslated_fallacies %}
                    <div class="fallacy{% if fallacy.fallacy.parent is not None %} child{% endif %}">
                        {% if fallacy.fallacy.image %}
                            <img src="{{ fallacy.fallacy.image.url }}"/>
                        {% else %}
                            <img src="{% static 'nietz/icon.svg' %}"/>
                        {% endif %}
                        <div>
                            <a href="{% url 'nietz:fallacy' fallacy.fallacy.id %}" class="name">{{ fallacy.name.capitalize }}</a>
                            <span class="description">{{ fallacy.description }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

source/templates/nietz/fallacy.html
{% extends 'nietz/base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="formatter fallacy-cover">
        {% if fallacy.fallacy.image %}
            <img src="{{ fallacy.fallacy.image.url }}">
        {% else %}
            <img src="{% static 'nietz/icon.svg' %}">
        {% endif %}
        <div class="fallacy-cover-title-categories">
            <div>
                <h1>{{ fallacy.name.capitalize }}</h1>
                <h2>{{ fallacy.fallacy.name.capitalize }}</h2>
            </div>
            <div>
                {% for category in fallacy.fallacy.categories.all %}
                    {# TODO Translate categories #}
                    <span class="fallacy-category" style="background-color: {{ category.color }}"
                          data-balloon="{{ category.name }}" data-balloon-pos="down">
                        {{ category.name }}
                    </span>
                {% endfor %}
            </div>
        </div>
        <p>{{ fallacy.description }}</p>
    </div>
    <div class="formatter">
        {{ fallacy.explanation_html|safe }}
        <h3>{% trans "Examples" %}:</h3>
        {% if fallacy.examples.exists %}
            <div class="fallacy-examples">
                {% for example in fallacy.examples.all %}
                    <div class="fallacy-example">
                        <span class="fallacy-example-text">{{ example.content_html|safe }}</span>
                        <div class="fallacy-example-explanation">{{ example.explanation_html|safe }}</div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            {% trans "No translated examples." %} <a href="#">{% trans "Contribute some!" %}</a>
        {% endif %}
        {% if children.exists or untranslated_children.exists %}
            <h3>{% trans "Cases of this fallacy" %}:</h3>
            <div class="fallacies">
                {% for child in children %}
                    <div class="fallacy">
                        {% if child.fallacy.image %}
                            <img src="{{ child.fallacy.image.url }}"/>
                        {% else %}
                            <img src="{% static 'nietz/icon.svg' %}"/>
                        {% endif %}
                        <div>
                            <a href="{% url 'nietz:fallacy' child.fallacy.id %}"
                               class="name">{{ child.name.capitalize }}</a>
                            <span class="description">{{ child.description }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% for child in untranslated_children %}
                {{ child.name }}
            {% endfor %}
        {% endif %}
        {% if related.exists or untranslated_related.exists %}
            <h3>{% trans "Related fallacies" %}:</h3>
            <div class="fallacies">
                {% for fallacy in related %}
                    <div class="fallacy">
                        {% if fallacy.fallacy.image %}
                            <img src="{{ fallacy.fallacy.image.url }}"/>
                        {% else %}
                            <img src="{% static 'nietz/icon.svg' %}"/>
                        {% endif %}
                        <div>
                            <a href="{% url 'nietz:fallacy' fallacy.fallacy.id %}"
                               class="name">{{ fallacy.name.capitalize }}</a>
                            <span class="description">{{ fallacy.description }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

source/templates/nietz/index.html
{% extends 'nietz/base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <nav id="index">
        <div class="index-pane" style="background-image: url('{% static 'nietz/basic-concepts.jpg' %}')">
            <div>
                <a href="{% url 'nietz:concepts' %}" class="index-pane-title">
                    <h1>{% trans "Understand basic concepts" %}</h1>
                    <span>{% trans "A quick guide through concepts you need to understand in order to argue properly." %}</span>
                </a>
            </div>
            <a class="index-pane-credit" href="https://500px.com/giamboscaro">Giammarco Boscaro</a>
        </div>
        <div class="index-pane" style="background-image: url('{% static 'nietz/fallacies.jpg' %}')">
            <div>
                <a href="{% url 'nietz:fallacies' %}" class="index-pane-title">
                    <h1>{% trans "Know discourse fallacies" %}</h1>
                    <span>{% trans "Looking good and being persuasive isn't enough, make your argument sound!" %}</span>
                </a>
            </div>
            <a class="index-pane-credit" href="https://acreativemess.nl">Micheile Henderson</a>
        </div>
        <div class="index-pane" style="background-image: url('{% static 'nietz/biases.jpg' %}')">
            <div>
                <a href="#" class="index-pane-title">
                    <h1>{% trans "Find your biases" %}</h1>
                    <span>{% trans "You're not only missing the point, you're losing your rationality!" %}</span>
                </a>
            </div>
            <a class="index-pane-credit" href="https://unsplash.com/@budhelisson">Bud Helisson</a>
        </div>
    </nav>
{% endblock %}